Library_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
   path('', views.home,name='home'),
   path('search/', views.search_book,name='search'),
   path('detail_info/<str:pk>/', views.detail_info_book,name='detail'),
   path('cart/', views.cart,name='cart'),
   path('remove_from_cart/<str:cart_pk>/', views.remove_from_cart,name='remove_from_cart'),

   path('login/', views.loginPage,name='login'),
   path('register/', views.register,name='register'),
   path('logout/', views.logoutUser, name='logout'),
   path('password_change/', views.password_change,name='password_change'),
   path('password_change_done/', views.password_change_done,name='password_change_done'),
   path('account/', views.accountSettings, name='account'),
   path('dashboard/', views.dashboard, name='dashboard'),

   
   path('librarian/', views.librarian_home, name="librarian"), 
   path('borrowers/', views.borrowers, name="borrowers"),
   path('register_reader/', views.register_reader, name="register_reader"),
   path('remove_reader/<str:reader_pk>/', views.remove_reader, name="remove_reader"),
   path('update_reader/<str:reader_pk>/', views.update_reader, name="update_reader"),
   path('request_onl_list/', views.request_onl_list, name="request_onl_list"),
   path('request_onl/<str:pk>/', views.request_onl, name="request_onl"),
   path('update_request/<str:pk>/', views.update_request, name="update_request"),
   path('borrow_detail/<str:pk>/', views.borrow_detail, name="borrow_detail"),
   path('request_off/', views.request_off, name="request_off"),
   path('return_book/<str:pk>/', views.return_book, name="return_book"),
   path('penalty_ticket/', views.penalty_ticket, name="penalty_ticket"),
   path('reader_borrow_detail/',views.reader_borrow_detail, name="reader_borrow_detail"),

   path('manager/manager_dashboard/', views.manager_dashboard, name="manager_dashboard"),
   path('manager/add_staff/', views.add_staff, name="add_staff"),
   path('manager/delete_staff/<str:sId>', views.delete_staff, name="delete_staff"),


   path('storekeeper/list_book/', views.list_book, name="list_book"),
   path('storekeeper/thanh_ly/', views.thanh_ly, name="thanh_ly"),
   path('storekeeper/liquidation_info/<str:bId>/', views.liquidation_info, name="liquidation_info"),
   path('storekeeper/add_book/', views.add_book, name="add_book"),
   path('storekeeper/liquidation_history/', views.liquidation_history, name="liquidation_history"),


   path('receipt_list/', views.receipt_list, name="receipt_list"),
   path('add_receipt/', views.add_receipt, name="add_receipt"),
   path('remove_receipt/<str:receipt_pk>/', views.remove_receipt, name="remove_receipt"),
   path('return_book_history/', views.return_book_history, name="return_book_history"),

]  

accounts/models.py
from email import message
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
import datetime
from .initial_func import pk_gen, staff_pk_gen, book_pk_gen
from jsonfield import JSONField
# from django.utils.translation import gettext as _
from django.contrib import messages

DEFAULT_PASSWORD = 'password'

class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    birth = models.DateField(null=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    profile_pic = models.ImageField(default="profile_pic.png", null=True, blank=True)
    date_created = models.DateTimeField(null=True, auto_now_add=True)
        
    def __str__(self):
        return self.name


class Staff(Customer):
    CETIFICATE = [
        ('Baccalaureate', 'Tú tài'), 
        ('Intermediate', 'Trung cấp'), 
        ('College1', 'Cao đẳng'), 
        ('College2', 'Đại học'), 
        ('Master', 'Thạc sĩ'), 
        ('Doctor', 'Tiến sĩ')
    ]
    POSITION = [
        ('President', 'Giám đốc'), 
        ('Vice President', 'Phó giám đốc'), 
        ('Manager', 'Trưởng phòng'), 
        ('Deputy', 'Phó phòng'), 
        ('Staff', 'Nhân viên'), 
    ]
    SERVICE = [
        ('Librarian', 'Thủ thư'), 
        ('Cashier', 'Thủ quỹ'), 
        ('storekeeper', 'Thủ kho'), 
        ('Manager department', 'Ban giám đốc'), 
    ]
    certificate = models.CharField(max_length=200, null=True, choices=CETIFICATE, blank=True)
    position = models.CharField(max_length=200, null=True, choices=POSITION)
    service = models.CharField(max_length=200, null=True, choices=SERVICE)
    sId = models.CharField(default=staff_pk_gen, primary_key=True, unique=True, max_length=255,editable=False)
    force_password_change = models.BooleanField(default=True)

class Reader(Customer):
    READER_TYPE = [
        ('Male', 'Nam'), 
        ('Female', 'Nữ')
    ]

    reader_type = models.CharField(max_length=200, null=True, choices=READER_TYPE, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    rId = models.CharField(default=pk_gen, primary_key=True, unique=True, max_length=255,editable=False)	
    card_maker = models.ForeignKey(Staff, null=True, on_delete=models.SET_NULL, blank=True)
    total_debt = models.PositiveIntegerField(null=True, default=0)
    def save(self, force_insert=False, force_update=False, using=None, 
             update_fields=None) -> None:
        # request = kwargs.get('request')
        # request = None
        # if self.request != None:
        #     request = self.request
        # else:
        #     request = kwargs.get('request')
        age = datetime.datetime.now().year - self.birth.year

        # # kiem tra xem tuoi cua doc gia co nam trong  18 den 55 khong
        # if age not in range(18, 56):
        #     messages.error(request, 'Tuổi của độc giả là {},độc giả phải có độ tuổi nằm trong 18 đến 55'.format(age))
        #     return None
                # kiem tra xem tuoi cua doc gia co nam trong  18 den 55 khong
        if age not in range(18, 56):
            raise Exception('Tuổi của độc giả là {},độc giả phải có độ tuổi nằm trong 18 đến 55'.format(age))


        return super().save(force_insert, force_update, using, update_fields)
    def is_out_of_date(self): # kiem tra xem the con han hay khong
        validate_value = datetime.datetime.now().month - self.date_created.month
        if validate_value > 6:
            return True
        return False



class BookCategory(models.Model):
    name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name
# class MyMaxValueValidator(MaxValueValidator):
#     message = _('Năm xuất bản không hợp lệ %(limit_value)s.')
# class MyMinValueValidator(MinValueValidator):
#     message = _('Chỉ được nhận sách xuất bản trong vòng 8 năm (từ %(limit_value)s).')

class Book(models.Model):

    bId = models.CharField(default=book_pk_gen, primary_key=True, unique=True, max_length=255,editable=False)	
    name = models.CharField(max_length=200, null=True)
    cover_pic = models.ImageField(default="logo.png", null=True, blank=True)
    ctg = models.ManyToManyField(BookCategory, blank=True)							# Category
    author = models.CharField(max_length=200, null=True, blank=True)
    price = models.PositiveIntegerField(null=True, default=0)
    publisher = models.CharField(max_length=200, null=True, blank=True)
    pubYear = models.PositiveIntegerField(null=True)
    addDate = models.DateTimeField(null=True, auto_now_add=True)
    total = models.PositiveIntegerField(null=True, default=1)
    number_of_book_remain = models.PositiveIntegerField(null=True, default=1)
    description = models.CharField(max_length=200000, null=True, blank=True)
    nguoinhan = models.ForeignKey(Staff, null=True, on_delete=models.SET_NULL, blank=True)

    def __str__(self):
        return self.name
    # def __init__(self, *args, **kwargs) -> None:
    #     self.request = None
    #     super().__init__(*args, **kwargs)
    def save(self, force_insert=False, force_update=False, using=None, 
             update_fields=None) -> None:
            
        if self.total < self.number_of_book_remain:
            raise Exception('Số lượng sách còn lại không được lớn hơn tổng số lượng sách.')
            
        ymin = datetime.date.today().year-8
        ymax = datetime.date.today().year+2 # do range(ymin, ymax-1)
        if self.pubYear not in range(ymin, ymax):
            raise Exception('Chỉ nhận sách xuất bản trong vòng 8 năm.')
        return super().save(force_insert, force_update, using, update_fields)

    def get_all_ctg_to_string(self):
        all_this_book_ctg = self.ctg.all()
        return ', '.join([ctg.name for ctg in all_this_book_ctg])
class Cart(models.Model):
    reader = models.ForeignKey(Reader, null=True, on_delete=models.SET_NULL, unique=False,  blank=True)
    book = models.ForeignKey(Book, null=True, on_delete=models.SET_NULL, blank=True)
    def save(self, force_insert=False, force_update=False, using=None, 
             update_fields=None) -> None:

        carts = Cart.objects.filter(reader=self.reader)

        if carts.count() >= 5:
            raise Exception('Độc giả chỉ được mượn tối đa 5 quyển sách một lúc')
        
        borrow_orders = BorrowOrder.objects.filter(reader=self.reader)
        
        count_books = 0
        for borrow_order in borrow_orders:
            print(borrow_order.list_book)
            if borrow_order.status == 'Chờ xác nhận':
                count_books += len(borrow_order.list_book)
        borrow_book = BorrowBook.objects.filter(reader=self.reader)
        for book in borrow_book:
            count_books += len(book.list_book)
        if count_books >= 5:
            print('raise exception')
            raise Exception('Độc giả chỉ được mượn tối đa 5 quyển sách một lúc')


        return super().save(force_insert, force_update, using, update_fields)

class BorrowOrder(models.Model):
    STATUS = [
        ('Chờ xác nhận','Chờ xác nhận'),
        ('Đang soạn sách', 'Đang soạn sách'), 
        ('Hoàn thành', 'Hoàn thành'),
        ('Đã nhận sách','Đã nhận sách')
    ]
    #cart = models.ForeignKey(Cart, null=True, on_delete=models.SET_NULL, unique=False,  blank=True)
    reader = models.ForeignKey(Reader, null=True, on_delete=models.SET_NULL, unique=False,  blank=True)
    list_book = JSONField()
    status = models.CharField(max_length=200, null=True, choices=STATUS, blank=True,default='Chờ xác nhận')

    def save(self, force_insert=False, force_update=False, using=None, 
             update_fields=None) -> None:

        borrow_orders = BorrowOrder.objects.filter(reader=self.reader)
        
        # count_books = 0
        # for borrow_order in borrow_orders:
        #     print(borrow_order.list_book)
        #     count_books += len(borrow_order.list_book)

        # if count_books >= 5:
        #     print('raise exception')
        #     raise Exception('Độc giả chỉ được mượn tối đa 5 quyển sách một lúc')

        return super().save(force_insert, force_update, using, update_fields)


class BorrowBook(models.Model):
    reader = models.ForeignKey(Reader, null=True, on_delete=models.SET_NULL, blank=True)
    list_book = JSONField()
    date_borrow = models.DateTimeField(null=True, auto_now_add=True)
    
    def save(self, force_insert=False, force_update=False, using=None, 
             update_fields=None) -> None:
        
        if self.reader.is_out_of_date():
            raise Exception('Thẻ quá hạn')

        borrow_books = BorrowBook.objects.filter(reader=self.reader)

        return super().save(force_insert, force_update, using, update_fields)
    
    def __str__(self):  
        return self.reader.name
    
class ReturnBook(models.Model):
    reader = models.ForeignKey(Reader, null=True, on_delete=models.SET_NULL, blank=True)
    book = models.ForeignKey(Book, null=True, on_delete=models.SET_NULL, blank=True)
    date_borrow = models.DateTimeField(null=True, auto_now_add=True)
    date_return = models.DateTimeField(null=True, auto_now_add=True)
    fine = models.PositiveIntegerField(null=True, default=0)
    def save(self, force_insert=False, force_update=False, using=None, 
             update_fields=None) -> None:
        return super().save(force_insert, force_update, using, update_fields)
    def save(self, force_insert=False, force_update=False, using=None, 
             update_fields=None) -> None:
        # Kiểm tra tiền thu không vượt quá tiền mượn
        if self.fine > self.reader.total_debt:

accounts/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User

from .models import *

class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'
        exclude = ['user']

class DateInput(forms.DateInput):
    input_type = 'date'

class ReaderForm(ModelForm):
    class Meta:
        model = Reader
        fields = ['name','reader_type','address','birth','email']
        widgets = {
            'birth': DateInput()
        }
        

class StaffForm(ModelForm):
    position = forms.ChoiceField(choices=[
            ('Manager', 'Trưởng phòng'),
            ('Staff', 'Nhân viên'), 
        ], 
        required=True)
    class Meta:
        model = Staff
        fields = '__all__'

        exclude = ['sId','user','force_password_change']
        widgets = {
            'birth': DateInput()
        }
    def __init__(self,*args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[str(field)].widget.attrs.update({'class': 'form-control'})
        self.fields['name'].label = 'Tên'
        self.fields['birth'].label = 'Ngày sinh'
        self.fields['address'].label = 'Địa chỉ'
        self.fields['profile_pic'].label = 'Ảnh đại diện'
        self.fields['profile_pic'].widget.clear_checkbox_label = 'Xóa'
        self.fields['profile_pic'].widget.initial_text  = 'Hiện tại'
        self.fields['profile_pic'].widget.input_text  = 'Chọn hình đại diện khác'
        self.fields['certificate'].label = 'Bằng cấp'
        self.fields['position'].label = 'Chức vụ'
        self.fields['service'].label = 'Bộ phận'


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class ChangePasswordForm(PasswordChangeForm):
    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']


class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = '__all__'
        exclude = ['bId','number_of_book_remain','nguoinhan','addDate']
        widgets = {
            'ctg': forms.CheckboxSelectMultiple()
        }
    def __init__(self,*args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        for field in self.fields:
            if str(field) != 'ctg':
                self.fields[str(field)].widget.attrs.update({'class': 'form-control'})

class OrderForm(ModelForm):
    class Meta:
        model = BorrowOrder
        fields = '__all__'
        exclude = ['list_book']
        
class BookLiquidationForm(ModelForm):
    class Meta:
        model = BookLiquidation
        fields = '__all__'

class ReceiptForm(ModelForm):
    class Meta:
        model = FineReceipt
        fields = ['debt', 'proceeds']

accounts/templates/pages/manager/delete_staff.html
{% extends 'pages/main/main.html' %}
{% load static %}

{% block content %}
<br>
<div class="row">
    <div class="col-md-6">
        <div class="card card-body">

            <p>Bạn có chắc muốn xóa nhân viên "{{staff.name}}"?</p>
            <form action="{% url 'delete_staff' staff.sId %}" method="POST">
                {% csrf_token %}
                <a class='btn btn-warning' href={% url 'manager_dashboard' %}>Trở lại</a>

                <input class='btn btn-danger' type="submit" value="Xác nhận">
            </form>
        </div>
    </div>
</div>
{% endblock content %}

accounts/templates/pages/manager/manager_dashboard.html
{% extends 'pages/table_form.html' %}
{% load static %}


{% block title_name %}
	<p>Danh sách nhân viên</p>

{% endblock title_name %}

{% block button %}
	<div class="add_button">
		<a href={% url 'add_staff' %} type="button" class="btn btn-primary" >Thêm nhân viên</a>
	</div>
{% endblock button %}
{% block filter %}
<div class="row">
	<div class="col">
		<div class="card card-body">
			<form method="get">
			<div class="form-row">
				<div class="form-group col">
					<label class="form-label" for="form2Example17">Tên nhân viên</label>
					{{staff_filter.form.name}}
				</div>
	
				<div class="form-group col">
					<label class="form-label" for="form2Example27">Mã nhân viên</label>
					{{staff_filter.form.sId}}
				</div>
				<div class="form-group col">
					<label class="form-label" for="form2Example17">Bằng cấp</label>
					{{staff_filter.form.certificate}}
				</div>
	
				<div class="form-group col">
					<label class="form-label" for="form2Example27">Chức vụ</label>
					{{staff_filter.form.position}}
				</div>
	
				<div class="form-group col">
					<label class="form-label" for="form2Example27">Bộ phận</label>
					{{staff_filter.form.service}}
				</div>
				
			</div>
			<button class="btn btn-primary" type="submit">Tìm</button>
		  </form>
		</div>
	</div>
</div>
<script>
						
    var form_fields = document.getElementsByTagName('input')
	var choice_fields = document.getElementsByTagName('select')

    for (var field in form_fields){	
        form_fields[field].className += 'form-control'
    }
	for (var field in choice_fields){	
		choice_fields[field].className += 'form-select'
	}

</script>

{% endblock filter %}


{% block table_head %}
<tr>
<th>Mã nhân viên</th>
<th>Họ tên</th>
<th>Ngày sinh</th>
<th>Địa chỉ</th>
<th>Ngày lập</th>
<th>Bằng cấp</th>
<th>Vị trí</th>
<th>Bộ phận</th>
<th>Tên tài khoản</th>
<th></th>
</tr>
{% endblock table_head %}
{% block table_body %}
	{% for i in staffs %}
		<tr>
			<th>{{i.pk}}</th>
			<th>{{i.name}}</th>
			<th>{{i.birth|date:'d-m-Y'}}</th>
			<th>{{i.address}}</th>
			<th>{{i.date_created|date:'d-m-Y'}}</th>
			<th>{{i.get_certificate_display}}</th>
			<th>{{i.get_position_display}}</th>
			<th>{{i.get_service_display}}</th>
			<th>{{i.user.username}}</th>
			{% comment %} <th><a type="submit" class="btn btn-outline-primary" href ="">Cập nhật</a></th> {% endcomment %}
			<th><a type="submit" class="btn btn-outline-danger" href ="{% url 'delete_staff' i.pk %}">Xóa nhân viên</a></th>	
		</tr>
	{% endfor %}
	{% if messages %}
	{% for message in messages %}
	<div class="alert {{ message.tags }} alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
		</button>
		{{ message }}
	</div>
	{% endfor %}
{% endif %}
{% endblock table_body %}

accounts/templates/pages/manager/register_staff.html
{% extends 'pages/main/main.html' %}
{% load static %}

{% block style %}
.form{
    margin: auto;
    margin-top:10px;
    padding: 40px 50px;
    width: 30%;
    background: #dbb7fd ;
    border-radius:10px;
}
.title_name{
    color:#4C3876 ;
    margin-bottom: 10px;
    font-weight: 800;
    font-size: 35px;
}
.col-12{
    margin-top: 30px;
}
{% endblock style %}


{% block content %}




<style>
	.profile-pic{
		max-width: 200px;
		max-height:200px;
		margin: 0 auto;
		border-radius: 50%;
	}
</style>

{% include 'pages/messages.html' %}

<div class="form">
    <div class="title_name">
		<div class="d-flex justify-content-center">
			<h3>Đăng ký nhân viên</h3>
		</div>
	</div>
    <form method="POST" action="" class="row g-3">
			{% csrf_token %}
			<div class="form-outline">
				<label class="form-label" for="form2Example17">Tên nhân viên</label>
				{{form.name}}
			</div>

			<div class="form-outline">
				<label class="form-label" for="form2Example27">Ngày sinh</label>
				{{form.birth}}
			</div>
            <div class="form-outline">
				<label class="form-label" for="form2Example17">Địa chỉ</label>
				{{form.address}}
			</div>

			<div class="form-outline">
				<label class="form-label" for="form2Example27">Ảnh đại diện</label>
				{{form.profile_pic}}
			</div>

			<div class="form-outline">
				<label class="form-label" for="form2Example27">Bằng cấp</label>
				{{form.certificate}}
			</div>

            <div class="form-outline">
				<label class="form-label" for="form2Example27">Vị trí</label>
				{{form.position}}
            </div>

			<div class="form-outline">
				<label class="form-label" for="form2Example27">Bộ phận</label>
				{{form.service}}
			</div>

			<input class="btn btn-primary" type="submit" name="update" value="Thêm nhân viên">

    </form>
</div>
<script>
						
    var form_fields = document.getElementsByTagName('input')
	var choice_fields = document.getElementsByTagName('select')

    for (var field in form_fields){	
        form_fields[field].className += ' form-control'
    }
	for (var field in choice_fields){	
		choice_fields[field].className += ' form-select'
	}

</script>

{% endblock %}